export const SEEDED_USERS = [
  {
    user: {
      id: 'user_abi',
      displayName: 'Abiola A.',
      handle: 'abiola',
      email: 'abiola@lethe.io',
      timezone: 'Africa/Lagos',
      location: 'Lagos, Nigeria',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['brainstorming', 'collaboration', 'career advice'],
      offers: ['design feedback', 'product thinking', 'ux critique'],
      asks: ['investor intros', 'go-to-market advice', 'founder mentoring'],
      userType: 'designer',
      preferredUserTypes: ['operator', 'investor', 'founder'],
      interests: ['design ethics', 'ai product design', 'systems thinking', 'effective altruism'],
      introText:
        'Product designer exploring AI and human communication. Looking for thoughtful builders and research-minded operators.',
      meetingFormat: 'video',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 1, startHour: 18, endHour: 20 },
      { dayOfWeek: 3, startHour: 19, endHour: 21 },
      { dayOfWeek: 6, startHour: 10, endHour: 12 },
    ],
  },
  {
    user: {
      id: 'user_elena',
      displayName: 'Elena Voss',
      handle: 'elena.voss',
      email: 'elena@lethe.io',
      timezone: 'Europe/Berlin',
      location: 'Berlin, Germany',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['collaboration', 'mentorship', 'brainstorming'],
      offers: ['design systems mentorship', 'hiring advice', 'portfolio reviews'],
      asks: ['career mentorship', 'design feedback', 'b2b founder peers'],
      userType: 'designer',
      preferredUserTypes: ['founder', 'operator', 'researcher'],
      interests: ['design ethics', 'systems thinking', 'architecture', 'ai product design'],
      introText:
        'Independent product designer focused on ethical design frameworks for emerging technology.',
      meetingFormat: 'video',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 1, startHour: 17, endHour: 19 },
      { dayOfWeek: 3, startHour: 17, endHour: 19 },
      { dayOfWeek: 5, startHour: 16, endHour: 18 },
    ],
  },
  {
    user: {
      id: 'user_james',
      displayName: 'James Okafor',
      handle: 'james.okafor',
      email: 'james@lethe.io',
      timezone: 'Africa/Lagos',
      location: 'Lagos, Nigeria',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['business development', 'brainstorming', 'collaboration'],
      offers: ['investor intros', 'partnership strategy', 'africa market insight'],
      asks: ['product design support', 'ux research help', 'design leadership coaching'],
      userType: 'founder',
      preferredUserTypes: ['designer', 'operator', 'researcher'],
      interests: ['b2b saas', 'african tech ecosystem', 'calm companies', 'product design'],
      introText: 'SaaS founder building for African businesses and looking for design-thinking collaborators.',
      meetingFormat: 'video',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 1, startHour: 18, endHour: 20 },
      { dayOfWeek: 2, startHour: 18, endHour: 20 },
      { dayOfWeek: 4, startHour: 19, endHour: 21 },
    ],
  },
  {
    user: {
      id: 'user_sophia',
      displayName: 'Sophia Chen',
      handle: 'sophia.chen',
      email: 'sophia@lethe.io',
      timezone: 'Europe/London',
      location: 'London, UK',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['research exchange', 'collaboration', 'brainstorming'],
      offers: ['research methods', 'experiment design', 'memory studies insight'],
      asks: ['startup data access', 'product collaboration', 'operator context'],
      userType: 'researcher',
      preferredUserTypes: ['founder', 'operator', 'designer'],
      interests: ['ai research', 'cognitive science', 'memory studies', 'ethics'],
      introText: 'Research scientist studying memory and decision-making in AI-mediated environments.',
      meetingFormat: 'video',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 1, startHour: 16, endHour: 18 },
      { dayOfWeek: 3, startHour: 16, endHour: 18 },
      { dayOfWeek: 5, startHour: 15, endHour: 17 },
    ],
  },
  {
    user: {
      id: 'user_river',
      displayName: 'River Castillo',
      handle: 'river.castillo',
      email: 'river@lethe.io',
      timezone: 'America/Mexico_City',
      location: 'Mexico City, Mexico',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['brainstorming', 'knowledge sharing', 'research exchange'],
      offers: ['ux research', 'community building', 'open-source tooling'],
      asks: ['creative technologists', 'design collaborators', 'research partners'],
      userType: 'researcher',
      preferredUserTypes: ['designer', 'researcher', 'engineer'],
      interests: ['ux research', 'complexity theory', 'design systems', 'open source'],
      introText: 'UX researcher curious about complex systems and where design meets research.',
      meetingFormat: 'voice',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 2, startHour: 16, endHour: 18 },
      { dayOfWeek: 4, startHour: 16, endHour: 18 },
      { dayOfWeek: 6, startHour: 11, endHour: 13 },
    ],
  },
  {
    user: {
      id: 'user_noah',
      displayName: 'Noah Bekele',
      handle: 'noah.bekele',
      email: 'noah@lethe.io',
      timezone: 'Africa/Nairobi',
      location: 'Nairobi, Kenya',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['collaboration', 'brainstorming', 'mentorship'],
      offers: ['climate operations insight', 'founder mentorship', 'partnership intros'],
      asks: ['design systems support', 'research rigor', 'fundraising intros'],
      userType: 'founder',
      preferredUserTypes: ['designer', 'researcher', 'investor'],
      interests: ['climate tech', 'infrastructure', 'thoughtful design', 'long-form reading'],
      introText: 'Climate tech founder building resilience infrastructure and seeking design-heavy thinkers.',
      meetingFormat: 'video',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 1, startHour: 19, endHour: 21 },
      { dayOfWeek: 3, startHour: 19, endHour: 21 },
      { dayOfWeek: 5, startHour: 19, endHour: 21 },
    ],
  },
  {
    user: {
      id: 'user_iris',
      displayName: 'Iris Morrow',
      handle: 'iris.morrow',
      email: 'iris@lethe.io',
      timezone: 'America/New_York',
      location: 'New York, USA',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['mentorship', 'career advice', 'collaboration'],
      offers: ['career mentorship', 'leadership coaching', 'operator hiring intros'],
      asks: ['research collaboration', 'ai product peers', 'climate founders'],
      userType: 'operator',
      preferredUserTypes: ['researcher', 'founder', 'operator'],
      interests: ['design leadership', 'design systems', 'mentoring', 'team building'],
      introText: 'Design leader mentoring one builder this quarter and focused on long-term team quality.',
      meetingFormat: 'video',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 2, startHour: 16, endHour: 18 },
      { dayOfWeek: 4, startHour: 16, endHour: 18 },
      { dayOfWeek: 6, startHour: 14, endHour: 16 },
    ],
  },
  {
    user: {
      id: 'user_yuki',
      displayName: 'Yuki Tanaka',
      handle: 'yuki.tanaka',
      email: 'yuki@lethe.io',
      timezone: 'Asia/Tokyo',
      location: 'Tokyo, Japan',
      isActive: true,
      matchingEnabled: true,
    },
    preferences: {
      matchIntent: ['collaboration', 'brainstorming', 'knowledge sharing'],
      offers: ['creative coding support', 'prototype feedback', 'maker community intros'],
      asks: ['product strategy mentors', 'distribution operators', 'founder peers'],
      userType: 'engineer',
      preferredUserTypes: ['founder', 'operator', 'designer'],
      interests: ['creative coding', 'generative art', 'tools for creators', 'design systems'],
      introText: 'Creative technologist building generative tools for artists and searching for design collaborators.',
      meetingFormat: 'voice',
      localOnly: false,
      matchEnabled: true,
      blockedUserIds: [],
    },
    availability: [
      { dayOfWeek: 1, startHour: 21, endHour: 23 },
      { dayOfWeek: 3, startHour: 21, endHour: 23 },
      { dayOfWeek: 6, startHour: 9, endHour: 11 },
    ],
  },
];

export const DEFAULT_ADMIN_ID = 'admin_trial';
